import { Controller, HttpCode, HttpStatus, Post, Req } from '@nestjs/common';
import type { RawBodyRequest } from '@nestjs/common';
import {
  ApiBadRequestResponse,
  ApiConsumes,
  ApiHeader,
  ApiOkResponse,
  ApiOperation,
  ApiProduces,
  ApiTags,
  ApiUnauthorizedResponse,
} from '@nestjs/swagger';
import type { Request } from 'express';
import { ApiErrorDto } from '../common/dto/api-error.dto';
import { ShopifyWebhookReceiptDto } from './dto/shopify-response.dto';
import { ShopifyWebhookService } from './shopify-webhook.service';

@ApiTags('Shopify Webhooks')
@ApiConsumes('application/json')
@ApiProduces('application/json')
@Controller('webhooks/shopify')
export class ShopifyWebhookController {
  constructor(private readonly webhookService: ShopifyWebhookService) {}

  @Post()
  @HttpCode(HttpStatus.OK)
  @ApiOperation({
    summary: 'Receive a Shopify webhook',
    description:
      'Public endpoint for app/uninstalled and mandatory privacy topics. The HMAC is verified against the exact raw request body before processing. Duplicate webhook IDs are acknowledged idempotently.',
  })
  @ApiHeader({
    name: 'X-Shopify-Hmac-Sha256',
    required: true,
    description: 'Base64 HMAC-SHA256 signature generated by Shopify.',
  })
  @ApiHeader({
    name: 'X-Shopify-Topic',
    required: true,
    example: 'app/uninstalled',
  })
  @ApiHeader({
    name: 'X-Shopify-Shop-Domain',
    required: true,
    example: 'atlas-market.myshopify.com',
  })
  @ApiHeader({
    name: 'X-Shopify-API-Version',
    required: true,
    example: '2026-07',
  })
  @ApiHeader({
    name: 'X-Shopify-Webhook-Id',
    required: true,
    example: 'b54557e4-bdd9-4b37-8a5f-bf7d70bcd043',
  })
  @ApiOkResponse({
    description: 'Webhook verified and acknowledged.',
    type: ShopifyWebhookReceiptDto,
  })
  @ApiBadRequestResponse({
    description: 'Missing raw body or malformed JSON.',
    type: ApiErrorDto,
  })
  @ApiUnauthorizedResponse({
    description: 'Missing/invalid Shopify HMAC or required webhook headers.',
    type: ApiErrorDto,
  })
  handle(@Req() request: RawBodyRequest<Request>) {
    return this.webhookService.handle(request, request.rawBody);
  }
}
