client_id = "bb2d05d7742822b671c834ef936ff055"

name = "zomaal"
application_url = "https://zomaal.onrender.com"
embedded = false

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

[access_scopes]
scopes = "read_products,read_orders,read_customers"
optional_scopes = []
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "http://localhost:3001/auth/shopify/callback",
  "https://zomaal.onrender.com/auth/shopify/callback"
]
