client_id = "bb2d05d7742822b671c834ef936ff055"

name = "zomaal"
application_url = "https://zomaal-backend-828793303867.us-central1.run.app/"
embedded = false

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

[[webhooks.subscriptions]]
topics = [
  "app/uninstalled",
  "orders/create",
  "orders/updated",
  "orders/cancelled",
  "orders/delete",
  "refunds/create",
  "products/create",
  "products/update",
  "products/delete",
  "customers/create",
  "customers/update",
  "customers/delete"
]
uri = "/webhooks/shopify"

[[webhooks.subscriptions]]
compliance_topics = [
  "customers/data_request",
  "customers/redact",
  "shop/redact"
]
uri = "/webhooks/shopify"

[access_scopes]
scopes = "read_products,read_orders,read_customers"
optional_scopes = []
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "http://localhost:3001/auth/shopify/callback",
  "https://zomaal-backend-828793303867.us-central1.run.app/auth/shopify/callback"
]
