import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import {
  InventoryBarcodeType,
  InventoryItemKind,
  WarehouseProductStatus,
} from '@prisma/client';
import { Type } from 'class-transformer';
import {
  ArrayMaxSize,
  ArrayMinSize,
  IsArray,
  IsEnum,
  IsInt,
  IsOptional,
  IsString,
  IsUUID,
  MaxLength,
  Max,
  Min,
  MinLength,
  ValidateNested,
} from 'class-validator';

export enum BarcodeLabelFormat {
  PDF = 'pdf',
  SVG = 'svg',
}

export enum BarcodeLabelTemplate {
  THERMAL_50X30 = 'THERMAL_50X30',
  THERMAL_60X40 = 'THERMAL_60X40',
  THERMAL_100X50 = 'THERMAL_100X50',
}

export class ValidateBarcodeDto {
  @ApiProperty({
    description:
      'Decoded barcode text. EAN, UPC, and GTIN values are check-digit validated. Merchant-specific identifiers should use OTHER.',
    example: '6291041500213',
  })
  @IsString()
  @MinLength(3)
  @MaxLength(100)
  value: string;

  @ApiPropertyOptional({
    enum: InventoryBarcodeType,
    description:
      'Omit to infer the type. INTERNAL_CODE_128 is reserved for ZML-XXXXXXXXXXXX values generated by Zomaal.',
  })
  @IsOptional()
  @IsEnum(InventoryBarcodeType)
  type?: InventoryBarcodeType;
}

export class GeneratedBarcodeResponseDto {
  @ApiProperty({ example: 'ZML-A1B2C3D4E5F6' })
  value: string;

  @ApiProperty({ enum: InventoryBarcodeType })
  type: InventoryBarcodeType;
}

export class BarcodeValidationResponseDto extends GeneratedBarcodeResponseDto {
  @ApiProperty({
    description:
      'True when no inventory item in the authenticated merchant store currently uses this value.',
    example: true,
  })
  available: boolean;
}

export class WarehouseBarcodeDto extends GeneratedBarcodeResponseDto {
  @ApiProperty({ format: 'uuid' })
  id: string;

  @ApiProperty({ example: true })
  isPrimary: boolean;

  @ApiProperty({ enum: ['ZOMAAL', 'MERCHANT'], example: 'ZOMAAL' })
  source: string;
}

export class ResolveBarcodeQueryDto {
  @ApiProperty({
    description:
      'Exact text decoded by the scanner. Surrounding whitespace is removed and Zomaal internal values are normalized to uppercase.',
    example: 'ZML-A1B2C3D4E5F6',
    minLength: 3,
    maxLength: 100,
  })
  @IsString()
  @MinLength(3)
  @MaxLength(100)
  value: string;
}

export class BarcodeLabelQueryDto {
  @ApiPropertyOptional({
    enum: BarcodeLabelFormat,
    default: BarcodeLabelFormat.PDF,
    description:
      'PDF is the printer-neutral production format. SVG is intended for browser preview and client-side printing.',
  })
  @IsOptional()
  @IsEnum(BarcodeLabelFormat)
  format?: BarcodeLabelFormat;

  @ApiPropertyOptional({
    enum: BarcodeLabelTemplate,
    default: BarcodeLabelTemplate.THERMAL_60X40,
    description: 'Physical sticker size in millimetres.',
  })
  @IsOptional()
  @IsEnum(BarcodeLabelTemplate)
  template?: BarcodeLabelTemplate;
}

export class BatchBarcodeLabelItemDto {
  @ApiProperty({
    format: 'uuid',
    description: 'Inventory barcode ID returned by a product or scan response.',
  })
  @IsUUID()
  barcodeId: string;

  @ApiProperty({ minimum: 1, maximum: 100, example: 2 })
  @IsInt()
  @Min(1)
  @Max(100)
  quantity: number;
}

export class BatchBarcodeLabelsDto {
  @ApiProperty({
    type: [BatchBarcodeLabelItemDto],
    minItems: 1,
    maxItems: 100,
    description:
      'Labels are emitted in this order. The combined quantity may not exceed 200 labels.',
  })
  @IsArray()
  @ArrayMinSize(1)
  @ArrayMaxSize(100)
  @ValidateNested({ each: true })
  @Type(() => BatchBarcodeLabelItemDto)
  items: BatchBarcodeLabelItemDto[];

  @ApiPropertyOptional({
    enum: BarcodeLabelTemplate,
    default: BarcodeLabelTemplate.THERMAL_60X40,
  })
  @IsOptional()
  @IsEnum(BarcodeLabelTemplate)
  template?: BarcodeLabelTemplate;
}

export class ResolvedBarcodeInventoryDto {
  @ApiProperty({ example: 100 })
  onHand: number;

  @ApiProperty({ example: 5 })
  reserved: number;

  @ApiProperty({ example: 1 })
  damaged: number;

  @ApiProperty({ example: 20 })
  incoming: number;

  @ApiProperty({
    description: 'onHand - reserved - damaged across all locations.',
    example: 94,
  })
  available: number;
}

export class ResolvedBarcodeProductDto {
  @ApiProperty({ format: 'uuid' })
  id: string;

  @ApiProperty({ example: 'Wireless Noise-Cancelling Headphones' })
  name: string;

  @ApiProperty({ enum: WarehouseProductStatus })
  status: WarehouseProductStatus;
}

export class ResolvedBarcodeVariantDto {
  @ApiProperty({ format: 'uuid' })
  id: string;

  @ApiProperty({ example: 'Black / XL' })
  title: string;

  @ApiProperty({ nullable: true, example: 'HEADPHONE-BLACK-XL' })
  sku: string | null;

  @ApiProperty({ example: 249.99 })
  price: number;

  @ApiProperty({ example: 120 })
  costPrice: number;

  @ApiProperty({ example: 5 })
  lowStockAlertThreshold: number;
}

export class ResolvedBarcodePackagingDto {
  @ApiProperty({ format: 'uuid' })
  id: string;

  @ApiProperty({ example: 'Large corrugated box' })
  name: string;

  @ApiProperty({ nullable: true, example: 'BOX-LARGE' })
  sku: string | null;

  @ApiProperty({ example: true })
  isActive: boolean;
}

export class ResolvedBarcodeResponseDto {
  @ApiProperty({ type: WarehouseBarcodeDto })
  barcode: WarehouseBarcodeDto;

  @ApiProperty({ format: 'uuid' })
  inventoryItemId: string;

  @ApiProperty({ enum: InventoryItemKind })
  inventoryItemKind: InventoryItemKind;

  @ApiProperty({ nullable: true, type: ResolvedBarcodeProductDto })
  product: ResolvedBarcodeProductDto | null;

  @ApiProperty({ nullable: true, type: ResolvedBarcodeVariantDto })
  variant: ResolvedBarcodeVariantDto | null;

  @ApiProperty({ nullable: true, type: ResolvedBarcodePackagingDto })
  packagingMaterial: ResolvedBarcodePackagingDto | null;

  @ApiProperty({ type: ResolvedBarcodeInventoryDto })
  inventory: ResolvedBarcodeInventoryDto;
}
