import {
  BadRequestException,
  ConflictException,
  Injectable,
  NotFoundException,
} from '@nestjs/common';
import {
  ExpensePaymentMethod,
  SalaryExpenseHandling,
  SalaryFrequency,
  SalaryPaymentMethod,
  SalaryPaymentStatus,
  StaffStatus,
  type StaffSalaryPayment,
  type StaffSalaryProfile,
} from '@prisma/client';
import { PrismaService } from '../prisma/prisma.service';
import { StoreAccessService } from '../access/store-access.service';
import {
  CreateSalaryPaymentDto,
  SalaryPaymentBatchResponseDto,
  SalaryPaymentListQueryDto,
  SalaryPaymentListResponseDto,
  SalaryPaymentResponseDto,
  SalaryProfileResponseDto,
  SetSalaryProfileDto,
} from './dto/staff-salary.dto';

const SALARY_PAYMENT_METHOD_TO_EXPENSE: Record<SalaryPaymentMethod, ExpensePaymentMethod> = {
  BANK_TRANSFER: ExpensePaymentMethod.BANK,
  CASH: ExpensePaymentMethod.CASH,
};

@Injectable()
export class StaffSalaryService {
  constructor(
    private readonly prisma: PrismaService,
    private readonly storeAccess: StoreAccessService,
  ) {}

  async getProfile(
    userId: string,
    staffId: string,
  ): Promise<{ profile: SalaryProfileResponseDto | null }> {
    const { storeId } = await this.storeAccess.requireOwner(userId);
    await this.requireStaff(storeId, staffId);

    const profile = await this.prisma.staffSalaryProfile.findUnique({
      where: { staffMemberId: staffId },
    });

    return { profile: profile ? toProfileResponse(profile) : null };
  }

  async setProfile(
    userId: string,
    staffId: string,
    dto: SetSalaryProfileDto,
  ): Promise<SalaryProfileResponseDto> {
    const { storeId } = await this.storeAccess.requireOwner(userId);
    await this.requireStaff(storeId, staffId);

    const startDate = new Date(dto.startDate);
    const expenseHandling = dto.expenseHandling ?? SalaryExpenseHandling.AUTOMATIC;

    const existing = await this.prisma.staffSalaryProfile.findUnique({
      where: { staffMemberId: staffId },
    });

    const profile = await this.prisma.staffSalaryProfile.upsert({
      where: { staffMemberId: staffId },
      create: {
        staffMemberId: staffId,
        baseSalary: dto.baseSalary,
        frequency: dto.frequency,
        paymentMethod: dto.paymentMethod,
        expenseHandling,
        startDate,
        // First automatic payment is due on the schedule's own start date.
        nextPaymentDate: expenseHandling === SalaryExpenseHandling.AUTOMATIC ? startDate : null,
        notes: dto.notes ?? null,
      },
      update: {
        baseSalary: dto.baseSalary,
        frequency: dto.frequency,
        paymentMethod: dto.paymentMethod,
        expenseHandling,
        startDate,
        notes: dto.notes,
        // Switching MANUAL -> AUTOMATIC (re)starts the schedule from today if
        // nothing is already pending; switching to MANUAL clears it, since a
        // human is now responsible for every entry.
        nextPaymentDate:
          expenseHandling === SalaryExpenseHandling.AUTOMATIC
            ? (existing?.nextPaymentDate ?? startDate)
            : null,
      },
    });

    return toProfileResponse(profile);
  }

  async listPayments(
    userId: string,
    staffId: string,
    query: SalaryPaymentListQueryDto,
  ): Promise<SalaryPaymentListResponseDto> {
    const { storeId } = await this.storeAccess.requireOwner(userId);
    const staff = await this.requireStaff(storeId, staffId);

    const page = query.page ?? 1;
    const limit = query.limit ?? 20;

    const [payments, total] = await Promise.all([
      this.prisma.staffSalaryPayment.findMany({
        where: { staffMemberId: staffId },
        orderBy: { paymentDate: 'desc' },
        skip: (page - 1) * limit,
        take: limit,
      }),
      this.prisma.staffSalaryPayment.count({ where: { staffMemberId: staffId } }),
    ]);

    return {
      payments: payments.map((p) => toPaymentResponse(p, staff.name)),
      total,
    };
  }

  /**
   * Manual salary entry (Add Salary Record: choose staff, then enter the
   * payment). Blocked per staff member whose profile is AUTOMATIC — that
   * person's salary is generated by runAutomaticPayments instead, and
   * letting both paths write would double-count the expense.
   */
  async createPayments(
    userId: string,
    dto: CreateSalaryPaymentDto,
  ): Promise<SalaryPaymentBatchResponseDto> {
    const { storeId } = await this.storeAccess.requireOwner(userId);

    const staffMembers = await this.prisma.staffMember.findMany({
      where: { id: { in: dto.staffMemberIds }, storeId },
      include: { salaryProfile: true },
    });

    const foundIds = new Set(staffMembers.map((s) => s.id));
    const missing = dto.staffMemberIds.filter((id) => !foundIds.has(id));
    if (missing.length > 0) {
      throw new NotFoundException(`Staff member(s) not found: ${missing.join(', ')}`);
    }

    const automatic = staffMembers.filter(
      (s) => s.salaryProfile?.expenseHandling === SalaryExpenseHandling.AUTOMATIC,
    );
    if (automatic.length > 0) {
      throw new ConflictException(
        `Manual salary entry is blocked while automatic is on for: ${automatic
          .map((s) => s.name)
          .join(', ')}`,
      );
    }

    const missingAmount = !dto.amount;
    const noProfileNoAmount = staffMembers.filter(
      (s) => missingAmount && !s.salaryProfile,
    );
    if (noProfileNoAmount.length > 0) {
      throw new BadRequestException(
        `Amount is required for staff with no salary profile set: ${noProfileNoAmount
          .map((s) => s.name)
          .join(', ')}`,
      );
    }

    const categoryId = await this.resolveSalaryCategoryId(storeId);
    const paymentDate = new Date(dto.paymentDate);

    const payments = await Promise.all(
      staffMembers.map((staff) => {
        const amount = dto.amount ?? staff.salaryProfile!.baseSalary.toString();
        return this.prisma.staffSalaryPayment.create({
          data: {
            staffMember: { connect: { id: staff.id } },
            amount,
            paymentDate,
            paidAt: new Date(),
            paymentMethod: dto.paymentMethod,
            status: SalaryPaymentStatus.PAID,
            notes: dto.notes ?? null,
            receiptUrl: dto.receiptUrl ?? null,
            expense: {
              create: {
                storeId,
                title: `Salary — ${staff.name}`,
                amount,
                paymentMethod: SALARY_PAYMENT_METHOD_TO_EXPENSE[dto.paymentMethod],
                spentAt: paymentDate,
                categoryId,
                staffMemberId: staff.id,
                createdByUserId: userId,
              },
            },
          },
        });
      }),
    );

    return {
      payments: payments.map((p, i) => toPaymentResponse(p, staffMembers[i].name)),
    };
  }

  /**
   * Called only by the internal scheduler (staff-salary-scheduler.controller)
   * — processes every AUTOMATIC profile whose nextPaymentDate has arrived,
   * across every store. One period per run; a run that fires at least as
   * often as the shortest frequency (DAILY) never falls behind.
   */
  async runAutomaticPayments(): Promise<{ processed: number }> {
    const due = await this.prisma.staffSalaryProfile.findMany({
      where: {
        expenseHandling: SalaryExpenseHandling.AUTOMATIC,
        nextPaymentDate: { lte: new Date() },
      },
      include: { staffMember: { select: { id: true, name: true, storeId: true, status: true } } },
    });

    let processed = 0;
    for (const profile of due) {
      // A deactivated staff member's automatic schedule stops generating
      // expenses, but the profile is left alone in case they're reactivated.
      if (profile.staffMember.status !== StaffStatus.ACTIVE) continue;

      const categoryId = await this.resolveSalaryCategoryId(profile.staffMember.storeId);
      const paymentDate = profile.nextPaymentDate!;

      await this.prisma.staffSalaryPayment.create({
        data: {
          staffMember: { connect: { id: profile.staffMemberId } },
          amount: profile.baseSalary,
          paymentDate,
          paidAt: new Date(),
          paymentMethod: profile.paymentMethod,
          status: SalaryPaymentStatus.PAID,
          expense: {
            create: {
              storeId: profile.staffMember.storeId,
              title: `Salary — ${profile.staffMember.name}`,
              amount: profile.baseSalary,
              paymentMethod: SALARY_PAYMENT_METHOD_TO_EXPENSE[profile.paymentMethod],
              spentAt: paymentDate,
              categoryId,
              staffMemberId: profile.staffMemberId,
            },
          },
        },
      });

      await this.prisma.staffSalaryProfile.update({
        where: { id: profile.id },
        data: { nextPaymentDate: advance(paymentDate, profile.frequency) },
      });

      processed += 1;
    }

    return { processed };
  }

  private async requireStaff(storeId: string, staffId: string) {
    const staff = await this.prisma.staffMember.findFirst({
      where: { id: staffId, storeId },
    });
    if (!staff) {
      throw new NotFoundException('Staff member not found');
    }
    return staff;
  }

  private async resolveSalaryCategoryId(storeId: string): Promise<string> {
    const existing = await this.prisma.expenseCategory.findFirst({
      where: { storeId, group: 'SALARY' },
      select: { id: true },
    });
    if (existing) return existing.id;

    const created = await this.prisma.expenseCategory.create({
      data: { storeId, name: 'Salaries', group: 'SALARY', isSystem: true },
      select: { id: true },
    });
    return created.id;
  }
}

function advance(date: Date, frequency: SalaryFrequency): Date {
  const next = new Date(date);
  switch (frequency) {
    case SalaryFrequency.DAILY:
      next.setDate(next.getDate() + 1);
      break;
    case SalaryFrequency.WEEKLY:
      next.setDate(next.getDate() + 7);
      break;
    case SalaryFrequency.MONTHLY:
      next.setMonth(next.getMonth() + 1);
      break;
  }
  return next;
}

function toProfileResponse(profile: StaffSalaryProfile): SalaryProfileResponseDto {
  return {
    baseSalary: profile.baseSalary.toFixed(2),
    frequency: profile.frequency,
    paymentMethod: profile.paymentMethod,
    expenseHandling: profile.expenseHandling,
    startDate: profile.startDate.toISOString(),
    nextPaymentDate: profile.nextPaymentDate?.toISOString() ?? null,
    notes: profile.notes,
  };
}

function toPaymentResponse(
  payment: StaffSalaryPayment,
  staffName: string,
): SalaryPaymentResponseDto {
  return {
    id: payment.id,
    staffMemberId: payment.staffMemberId,
    staffName,
    amount: payment.amount.toFixed(2),
    paymentDate: payment.paymentDate.toISOString(),
    paidAt: payment.paidAt?.toISOString() ?? null,
    paymentMethod: payment.paymentMethod,
    status: payment.status,
    notes: payment.notes,
    receiptUrl: payment.receiptUrl,
  };
}
