import {
  BadRequestException,
  ConflictException,
  Injectable,
  NotFoundException,
} from '@nestjs/common';
import {
  ExpensePaymentMethod,
  SalaryExpenseHandling,
  SalaryFrequency,
  SalaryPaymentMethod,
  SalaryPaymentStatus,
  StaffStatus,
  type StaffSalaryPayment,
  type StaffSalaryProfile,
} from '@prisma/client';
import { PrismaService } from '../prisma/prisma.service';
import { StoreAccessService } from '../access/store-access.service';
import {
  CreateSalaryPaymentDto,
  SalaryPaymentBatchResponseDto,
  SalaryPaymentListQueryDto,
  SalaryPaymentListResponseDto,
  SalaryPaymentResponseDto,
  SalaryProfileResponseDto,
  SetSalaryProfileDto,
} from './dto/staff-salary.dto';

const SALARY_PAYMENT_METHOD_TO_EXPENSE: Record<SalaryPaymentMethod, ExpensePaymentMethod> = {
  BANK_TRANSFER: ExpensePaymentMethod.BANK,
  CASH: ExpensePaymentMethod.CASH,
};

@Injectable()
export class StaffSalaryService {
  constructor(
    private readonly prisma: PrismaService,
    private readonly storeAccess: StoreAccessService,
  ) {}

  async getProfile(
    userId: string,
    staffId: string,
  ): Promise<{ profile: SalaryProfileResponseDto | null }> {
    const { storeId } = await this.storeAccess.requireOwner(userId);
    await this.requireStaff(storeId, staffId);

    const profile = await this.prisma.staffSalaryProfile.findUnique({
      where: { staffMemberId: staffId },
    });

    return { profile: profile ? toProfileResponse(profile) : null };
  }

  async setProfile(
    userId: string,
    staffId: string,
    dto: SetSalaryProfileDto,
  ): Promise<SalaryProfileResponseDto> {
    const { storeId } = await this.storeAccess.requireOwner(userId);
    await this.requireStaff(storeId, staffId);

    const startDate = new Date(dto.startDate);
    const expenseHandling = dto.expenseHandling ?? SalaryExpenseHandling.AUTOMATIC;

    const existing = await this.prisma.staffSalaryProfile.findUnique({
      where: { staffMemberId: staffId },
    });

    const profile = await this.prisma.staffSalaryProfile.upsert({
      where: { staffMemberId: staffId },
      create: {
        staffMemberId: staffId,
        baseSalary: dto.baseSalary,
        frequency: dto.frequency,
        paymentMethod: dto.paymentMethod,
        expenseHandling,
        startDate,
        // First automatic payment is due on the schedule's own start date.
        nextPaymentDate: expenseHandling === SalaryExpenseHandling.AUTOMATIC ? startDate : null,
        notes: dto.notes ?? null,
      },
      update: {
        baseSalary: dto.baseSalary,
        frequency: dto.frequency,
        paymentMethod: dto.paymentMethod,
        expenseHandling,
        startDate,
        notes: dto.notes,
        nextPaymentDate:
          expenseHandling === SalaryExpenseHandling.AUTOMATIC
            ? resolveNextPaymentDateOnUpdate(existing, startDate)
            : // Switching to MANUAL clears the schedule — a human is now
              // responsible for every entry.
              null,
      },
    });

    return toProfileResponse(profile);
  }

  async listPayments(
    userId: string,
    staffId: string,
    query: SalaryPaymentListQueryDto,
  ): Promise<SalaryPaymentListResponseDto> {
    const { storeId } = await this.storeAccess.requireOwner(userId);
    const staff = await this.requireStaff(storeId, staffId);

    const page = query.page ?? 1;
    const limit = query.limit ?? 20;

    const [payments, total] = await Promise.all([
      this.prisma.staffSalaryPayment.findMany({
        where: { staffMemberId: staffId },
        orderBy: { paymentDate: 'desc' },
        skip: (page - 1) * limit,
        take: limit,
      }),
      this.prisma.staffSalaryPayment.count({ where: { staffMemberId: staffId } }),
    ]);

    return {
      payments: payments.map((p) => toPaymentResponse(p, staff.name)),
      total,
    };
  }

  /**
   * Manual salary entry (Add Salary Record: choose staff, then enter the
   * payment). Blocked per staff member whose profile is AUTOMATIC — that
   * person's salary is generated by runAutomaticPayments instead, and
   * letting both paths write would double-count the expense.
   */
  async createPayments(
    userId: string,
    dto: CreateSalaryPaymentDto,
  ): Promise<SalaryPaymentBatchResponseDto> {
    const { storeId } = await this.storeAccess.requireOwner(userId);

    const staffMembers = await this.prisma.staffMember.findMany({
      where: { id: { in: dto.staffMemberIds }, storeId },
      include: { salaryProfile: true },
    });

    const foundIds = new Set(staffMembers.map((s) => s.id));
    const missing = dto.staffMemberIds.filter((id) => !foundIds.has(id));
    if (missing.length > 0) {
      throw new NotFoundException(`Staff member(s) not found: ${missing.join(', ')}`);
    }

    const automatic = staffMembers.filter(
      (s) => s.salaryProfile?.expenseHandling === SalaryExpenseHandling.AUTOMATIC,
    );
    if (automatic.length > 0) {
      throw new ConflictException(
        `Manual salary entry is blocked while automatic is on for: ${automatic
          .map((s) => s.name)
          .join(', ')}`,
      );
    }

    const missingAmount = !dto.amount;
    const noProfileNoAmount = staffMembers.filter(
      (s) => missingAmount && !s.salaryProfile,
    );
    if (noProfileNoAmount.length > 0) {
      throw new BadRequestException(
        `Amount is required for staff with no salary profile set: ${noProfileNoAmount
          .map((s) => s.name)
          .join(', ')}`,
      );
    }

    const categoryId = await this.resolveSalaryCategoryId(storeId);
    const paymentDate = new Date(dto.paymentDate);

    const payments = await Promise.all(
      staffMembers.map((staff) => {
        const amount = dto.amount ?? staff.salaryProfile!.baseSalary.toString();
        return this.prisma.staffSalaryPayment.create({
          data: {
            staffMember: { connect: { id: staff.id } },
            amount,
            paymentDate,
            paidAt: new Date(),
            paymentMethod: dto.paymentMethod,
            status: SalaryPaymentStatus.PAID,
            notes: dto.notes ?? null,
            receiptUrl: dto.receiptUrl ?? null,
            expense: {
              create: {
                storeId,
                title: `Salary — ${staff.name}`,
                amount,
                paymentMethod: SALARY_PAYMENT_METHOD_TO_EXPENSE[dto.paymentMethod],
                spentAt: paymentDate,
                categoryId,
                staffMemberId: staff.id,
                createdByUserId: userId,
              },
            },
          },
        });
      }),
    );

    return {
      payments: payments.map((p, i) => toPaymentResponse(p, staffMembers[i].name)),
    };
  }

  /**
   * Called only by the internal scheduler (staff-salary-scheduler.controller)
   * — processes every AUTOMATIC profile whose nextPaymentDate has arrived,
   * across every store. One period per run; a run that fires at least as
   * often as the shortest frequency (DAILY) never falls behind.
   */
  async runAutomaticPayments(): Promise<{ processed: number; skippedInactive: number }> {
    const due = await this.prisma.staffSalaryProfile.findMany({
      where: {
        expenseHandling: SalaryExpenseHandling.AUTOMATIC,
        nextPaymentDate: { lte: new Date() },
      },
      include: { staffMember: { select: { id: true, name: true, storeId: true, status: true } } },
    });

    let processed = 0;
    let skippedInactive = 0;
    for (const profile of due) {
      const paymentDate = profile.nextPaymentDate!;
      const nextPaymentDate = advance(paymentDate, profile.frequency, profile.startDate.getUTCDate());

      // A deactivated staff member's automatic schedule must still tick
      // forward — leaving nextPaymentDate frozen in the past would, on
      // reactivation, suddenly generate a back-dated payment for a period
      // they were inactive for the whole time. Advance without paying.
      if (profile.staffMember.status !== StaffStatus.ACTIVE) {
        await this.prisma.staffSalaryProfile.update({
          where: { id: profile.id },
          data: { nextPaymentDate },
        });
        skippedInactive += 1;
        continue;
      }

      const categoryId = await this.resolveSalaryCategoryId(profile.staffMember.storeId);

      await this.prisma.staffSalaryPayment.create({
        data: {
          staffMember: { connect: { id: profile.staffMemberId } },
          amount: profile.baseSalary,
          paymentDate,
          paidAt: new Date(),
          paymentMethod: profile.paymentMethod,
          status: SalaryPaymentStatus.PAID,
          expense: {
            create: {
              storeId: profile.staffMember.storeId,
              title: `Salary — ${profile.staffMember.name}`,
              amount: profile.baseSalary,
              paymentMethod: SALARY_PAYMENT_METHOD_TO_EXPENSE[profile.paymentMethod],
              spentAt: paymentDate,
              categoryId,
              staffMemberId: profile.staffMemberId,
            },
          },
        },
      });

      await this.prisma.staffSalaryProfile.update({
        where: { id: profile.id },
        data: { nextPaymentDate },
      });

      processed += 1;
    }

    return { processed, skippedInactive };
  }

  private async requireStaff(storeId: string, staffId: string) {
    const staff = await this.prisma.staffMember.findFirst({
      where: { id: staffId, storeId },
    });
    if (!staff) {
      throw new NotFoundException('Staff member not found');
    }
    return staff;
  }

  private async resolveSalaryCategoryId(storeId: string): Promise<string> {
    const existing = await this.prisma.expenseCategory.findFirst({
      where: { storeId, group: 'SALARY' },
      select: { id: true },
    });
    if (existing) return existing.id;

    const created = await this.prisma.expenseCategory.create({
      data: { storeId, name: 'Salaries', group: 'SALARY', isSystem: true },
      select: { id: true },
    });
    return created.id;
  }
}

/**
 * `anchorDay` is the day-of-month the schedule is meant to land on — the
 * profile's original startDate, NOT the previous payment's date. Deriving
 * the anchor from the previous payment instead would permanently drift a
 * schedule once it's clamped by a short month (Jan 31 -> Feb 28 -> Mar 28
 * forever, since 28 becomes the new "day"). Anchoring to startDate instead
 * gives Jan 31 -> Feb 28 -> Mar 31 -> Apr 30 -> May 31 — it returns to the
 * 31st every time a long-enough month comes back around.
 */
function resolveNextPaymentDateOnUpdate(
  existing: StaffSalaryProfile | null,
  newStartDate: Date,
): Date {
  // No profile yet, or it was MANUAL (nextPaymentDate already null): the
  // schedule starts fresh from the (possibly just-set) startDate.
  if (!existing || existing.nextPaymentDate === null) {
    return newStartDate;
  }
  // Already AUTOMATIC and startDate hasn't changed: this is an edit to some
  // other field (baseSalary, notes, ...) — leave the running schedule alone
  // rather than resetting it back to startDate on every unrelated save.
  if (existing.startDate.getTime() === newStartDate.getTime()) {
    return existing.nextPaymentDate;
  }
  // startDate was deliberately changed while already AUTOMATIC: honor it.
  return newStartDate;
}
export function advance(date: Date, frequency: SalaryFrequency, anchorDay: number): Date {
  switch (frequency) {
    case SalaryFrequency.DAILY: {
      const next = new Date(date);
      next.setUTCDate(next.getUTCDate() + 1);
      return next;
    }
    case SalaryFrequency.WEEKLY: {
      const next = new Date(date);
      next.setUTCDate(next.getUTCDate() + 7);
      return next;
    }
    case SalaryFrequency.MONTHLY:
      return addMonthClamped(date, anchorDay);
  }
}

function addMonthClamped(date: Date, anchorDay: number): Date {
  const firstOfTargetMonth = new Date(
    Date.UTC(
      date.getUTCFullYear(),
      date.getUTCMonth() + 1,
      1,
      date.getUTCHours(),
      date.getUTCMinutes(),
      date.getUTCSeconds(),
      date.getUTCMilliseconds(),
    ),
  );
  const lastDayOfTargetMonth = new Date(
    Date.UTC(firstOfTargetMonth.getUTCFullYear(), firstOfTargetMonth.getUTCMonth() + 1, 0),
  ).getUTCDate();
  firstOfTargetMonth.setUTCDate(Math.min(anchorDay, lastDayOfTargetMonth));
  return firstOfTargetMonth;
}

function toProfileResponse(profile: StaffSalaryProfile): SalaryProfileResponseDto {
  return {
    baseSalary: profile.baseSalary.toFixed(2),
    frequency: profile.frequency,
    paymentMethod: profile.paymentMethod,
    expenseHandling: profile.expenseHandling,
    startDate: profile.startDate.toISOString(),
    nextPaymentDate: profile.nextPaymentDate?.toISOString() ?? null,
    notes: profile.notes,
  };
}

function toPaymentResponse(
  payment: StaffSalaryPayment,
  staffName: string,
): SalaryPaymentResponseDto {
  return {
    id: payment.id,
    staffMemberId: payment.staffMemberId,
    staffName,
    amount: payment.amount.toFixed(2),
    paymentDate: payment.paymentDate.toISOString(),
    paidAt: payment.paidAt?.toISOString() ?? null,
    paymentMethod: payment.paymentMethod,
    status: payment.status,
    notes: payment.notes,
    receiptUrl: payment.receiptUrl,
  };
}
